"""Floquet-Liouvillian model for spin-torque-driven ESR-STM on a single molecular spin.

Core physics:
  * four many-body states |0>, |up>, |down>, |2>
  * coherent field-like torque (FLT) in the Hamiltonian
  * dissipative spin-transfer / damping-like torque (DLT) through time-dependent
    spin-selective Lindblad jump rates
  * exact restriction to the charge-superselected density-operator subspace
    { |0><0|, |up><up|, |up><down|, |down><up|, |down><down|, |2><2| }
  * Floquet propagator, slow Liouvillian exponents, exceptional-point diagnostics
  * tilted Floquet propagator for electron-counting current cumulants

The jump operators follow the four-state weak-coupling Lindblad construction used in
D. Ruckert et al., Phys. Rev. Research 8, 023121 (2026), Eqs. (19)-(27).

This implementation is intentionally layered: the experimentally measurable control
parameters Omega_F (coherent Rabi angular frequency), gamma_L and gamma_R (transport
rates), the ac modulation depth a_D, detuning, and tip polarization/angle can be fitted
without over-committing to a microscopic bias-to-coupling conversion.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
import numpy as np
from numpy.typing import NDArray
from scipy.linalg import expm, eig

HBAR_EV_S = 6.582119569e-16
H_EV_S = 4.135667696e-15
KB_EV_K = 8.617333262e-5
MU_B_EV_T = 5.7883818060e-5
E_CHARGE = 1.602176634e-19

# 4-state Hilbert basis: 0, up, down, 2
ket0 = np.array([1,0,0,0], complex)
ketu = np.array([0,1,0,0], complex)
ketd = np.array([0,0,1,0], complex)
ket2 = np.array([0,0,0,1], complex)

# exact charge-superselected operator basis (Hilbert-Schmidt orthonormal matrix units)
OP_BASIS = []
for a,b in [(0,0),(1,1),(1,2),(2,1),(2,2),(3,3)]:
    M = np.zeros((4,4), complex); M[a,b] = 1.0; OP_BASIS.append(M)
OP_BASIS = tuple(OP_BASIS)


def outer(a, b):
    return np.outer(a, b.conj())


def fermi(E_eV: float, mu_eV: float, T_K: float) -> float:
    x = (E_eV - mu_eV) / (KB_EV_K*T_K)
    if x > 40: return float(np.exp(-x))
    if x < -40: return 1.0 - float(np.exp(x))
    return float(1.0/(np.exp(x)+1.0))


def spinors(theta: float, phi: float = 0.0):
    """Tip majority/minority spinors in the z basis; Ruckert et al. Eqs. (17)-(18)."""
    cp, sp = np.cos(theta/2), np.sin(theta/2)
    plus = cp*np.exp(-0.5j*phi)*ketu + sp*np.exp(+0.5j*phi)*ketd
    minus = -sp*np.exp(-0.5j*phi)*ketu + cp*np.exp(+0.5j*phi)*ketd
    return plus, minus


@dataclass(frozen=True)
class Params:
    # molecular spectroscopy / electrostatics
    eps_eV: float = -0.350
    U_eV: float = 1.000
    T_K: float = 4.5
    mu_R_eV: float = 0.0
    V_dc_V: float = 0.800          # mu_L=e V numerically in eV for voltage in V

    # tip/substrate spin geometry
    p_L: float = 0.40
    p_R: float = 0.0
    theta: float = np.deg2rad(25.0)
    phi: float = 0.0

    # sequential tunnelling rate scales in s^-1 (Gamma_alpha / hbar)
    gamma_L: float = 8.0e7
    gamma_R: float = 1.0e9
    # ac-DLT rate modulation following Ruckert et al. Eq. (51):
    # gamma_L(t)=gamma_L^(0)+gamma_L^(1)[1+cos(wt+phi_D)]/2,
    # with a_D = gamma_L^(1)/gamma_L^(0).
    a_D: float = 0.60
    phi_D: float = 0.0

    # coherent spin dynamics in singly occupied sector
    f_drive_Hz: float = 12.94e9
    detuning_rad_s: float = 0.0    # omega0 - omega_drive
    Omega_F: float = 2*np.pi*9.0e6 # RWA Rabi angular frequency generated by coherent FLT
    phi_F: float = 0.0

    # extra intrinsic relaxation/dephasing in singly occupied spin sector
    T1_intrinsic_s: float = 140e-9
    Tphi_intrinsic_s: float = 2.0e-6
    g_factor: float = 2.0
    thermal_polarization: float | None = None

    # integration
    steps_per_period: int = 96

    @property
    def omega(self): return 2*np.pi*self.f_drive_Hz
    @property
    def period(self): return 1.0/self.f_drive_Hz
    @property
    def mu_L_eV(self): return self.V_dc_V
    @property
    def B_res_T(self):
        return H_EV_S*self.f_drive_Hz/(self.g_factor*MU_B_EV_T)


def h_spin(t: float, p: Params) -> NDArray[np.complex128]:
    """Hamiltonian divided by hbar (rad/s) on the full 4-state space.

    We work in a lab frame but remove the irrelevant common orbital energy. The drive
    convention H/hbar = omega0 sigma_z/2 + Omega_F cos(omega t+phi_F) sigma_x,
    so Omega_F is the RWA Rabi angular frequency.
    """
    omega0 = p.omega + p.detuning_rad_s
    c = np.cos(p.omega*t + p.phi_F)
    H = np.zeros((4,4), complex)
    H[1,1] = +0.5*omega0
    H[2,2] = -0.5*omega0
    H[1,2] = H[2,1] = p.Omega_F*c
    return H


def _raw_jumps_for_lead(alpha: str, t: float, p: Params):
    """Return [(C, q_count_R), ...] collapse matrices and right-lead count increments.

    q_count_R=+1 for an electron transferred from QD to R, -1 for R to QD, 0 otherwise.
    Rates implement Eqs. (24)-(27) of Ruckert et al. in s^-1 form.
    """
    if alpha == 'L':
        pol, theta, phi = p.p_L, p.theta, p.phi
        # Ruckert et al., PRR 8, 023121 (2026), Eq. (51).
        # p.gamma_L is gamma^(0); p.a_D = gamma^(1)/gamma^(0).
        base = p.gamma_L * (1.0 + 0.5*p.a_D*(1.0 + np.cos(p.omega*t+p.phi_D)))
        mu = p.mu_L_eV
    elif alpha == 'R':
        pol, theta, phi = p.p_R, 0.0, 0.0
        base = p.gamma_R
        mu = p.mu_R_eV
    else:
        raise ValueError(alpha)

    plus, minus = spinors(theta, phi)
    fe0 = fermi(p.eps_eV, mu, p.T_K)
    fe2 = fermi(p.eps_eV+p.U_eV, mu, p.T_K)
    fh0, fh2 = 1-fe0, 1-fe2

    # factors correspond to (1 +/- p)/2
    rp, rm = 0.5*(1+pol), 0.5*(1-pol)
    ops_rates = [
        (outer(plus, ket0),  base*fe0*rp),
        (outer(ket2, plus),  base*fe2*rm),
        (outer(minus, ket0), base*fe0*rm),
        (outer(ket2, minus), base*fe2*rp),
        (outer(ket0, plus),  base*fh0*rp),
        (outer(plus, ket2),  base*fh2*rm),
        (outer(ket0, minus), base*fh0*rm),
        (outer(minus, ket2), base*fh2*rp),
    ]
    out=[]
    for i,(L,r) in enumerate(ops_rates, start=1):
        if r <= 0: continue
        C=np.sqrt(r)*L
        q=0
        if alpha=='R':
            # n=1..4 charge dot from R => electron leaves R => q=-1
            # n=5..8 discharge dot to R => electron enters R => q=+1
            q = -1 if i<=4 else +1
        out.append((C,q))
    return out


def intrinsic_jumps(p: Params):
    """Thermal T1 + pure dephasing acting only in singly occupied sector."""
    if p.T1_intrinsic_s <= 0: return []
    # thermal equilibrium spin polarization along +z: r_z = tanh(hbar omega0/2kT)
    if p.thermal_polarization is None:
        E = H_EV_S*p.f_drive_Hz
        z_eq = np.tanh(E/(2*KB_EV_K*p.T_K))
    else:
        z_eq = p.thermal_polarization
    G1=1.0/p.T1_intrinsic_s
    # populations: gamma_up - gamma_down = G1*z_eq, sum=G1
    g_up=0.5*G1*(1+z_eq); g_down=0.5*G1*(1-z_eq)
    Lup = outer(ketu, ketd); Ldown = outer(ketd, ketu)
    out=[(np.sqrt(max(g_up,0))*Lup,0),(np.sqrt(max(g_down,0))*Ldown,0)]
    if p.Tphi_intrinsic_s>0 and np.isfinite(p.Tphi_intrinsic_s):
        # D[sigma_z] with coefficient gamma_phi/2 gives off-diagonal decay gamma_phi
        gamma_phi=1.0/p.Tphi_intrinsic_s
        Sz=np.zeros((4,4), complex); Sz[1,1]=1; Sz[2,2]=-1
        out.append((np.sqrt(gamma_phi/2)*Sz,0))
    return out


def liouvillian_action(rho: NDArray[np.complex128], t: float, p: Params, chi: float=0.0):
    H=h_spin(t,p)
    dr=-1j*(H@rho-rho@H)
    for C,q in _raw_jumps_for_lead('L',t,p)+_raw_jumps_for_lead('R',t,p)+intrinsic_jumps(p):
        CdC=C.conj().T@C
        jump=C@rho@C.conj().T
        if q and chi!=0.0: jump *= np.exp(1j*chi*q)
        dr += jump - 0.5*(CdC@rho+rho@CdC)
    return dr


def reduced_superop(t: float, p: Params, chi: float=0.0):
    """6x6 generator on the exact charge-superselected operator subspace."""
    L=np.zeros((6,6), complex)
    for j,B in enumerate(OP_BASIS):
        d=liouvillian_action(B,t,p,chi)
        for i,A in enumerate(OP_BASIS):
            L[i,j]=np.trace(A.conj().T@d)
    return L


def vector_to_rho(v):
    rho=sum(c*B for c,B in zip(v,OP_BASIS))
    return rho


def rho_to_vector(rho):
    return np.array([np.trace(B.conj().T@rho) for B in OP_BASIS], complex)


def floquet_map(p: Params, chi: float=0.0):
    """One-period propagator by midpoint exponential product."""
    n=p.steps_per_period; dt=p.period/n
    Phi=np.eye(6,dtype=complex)
    for k in range(n):
        t=(k+0.5)*dt
        Phi=expm(reduced_superop(t,p,chi)*dt)@Phi
    return Phi


def periodic_steady_state(p: Params):
    Phi=floquet_map(p,0.0)
    w,R=eig(Phi)
    k=np.argmin(np.abs(w-1.0))
    v=R[:,k]
    rho=vector_to_rho(v)
    rho=(rho+rho.conj().T)/2
    tr=np.trace(rho).real
    rho/=tr
    return rho, w[k], Phi


def floquet_exponents(p: Params):
    Phi=floquet_map(p,0.0)
    z=np.linalg.eigvals(Phi)
    mu=np.log(z)/p.period
    # quasifrequency folding to (-omega/2,omega/2]
    im=(mu.imag + 0.5*p.omega)%p.omega - 0.5*p.omega
    mu=mu.real + 1j*im
    return mu,z,Phi


def physical_slow_modes(p: Params, n=3):
    """Return the n nonstationary Floquet exponents closest to the imaginary axis."""
    mu,_,_=floquet_exponents(p)
    # discard stationary exponent
    ix=np.argsort(np.abs(mu))
    m=[]
    for k in ix:
        if abs(mu[k])<1e-3: continue
        m.append(mu[k])
        if len(m)==n: break
    return np.array(m)


def dissipative_gap(p: Params):
    mu,_,_=floquet_exponents(p)
    vals=[-x.real for x in mu if abs(x)>1e-3 and x.real<1e-6]
    return min(vals) if vals else np.nan


def eigen_condition_number(p: Params):
    Phi=floquet_map(p,0.0)
    w,R=np.linalg.eig(Phi)
    return float(np.linalg.cond(R))


def slow_pair_separation(p: Params):
    modes=physical_slow_modes(p,3)
    if len(modes)<2: return np.nan
    best=np.inf
    for i in range(len(modes)):
        for j in range(i+1,len(modes)):
            best=min(best,abs(modes[i]-modes[j]))
    return float(best)


def counting_cumulants(p: Params, h: float=2e-4):
    """Long-time net-electron counting cumulants per second through the right lead.

    For the tilted one-period map Phi_chi, lambda(chi)=log nu_max(chi)/T =
      i c1 chi - c2 chi^2/2 + O(chi^3).
    Returns c1 [electrons/s], c2 [electrons^2/s], Fano=c2/|c1|.
    """
    def lam(chi):
        z=np.linalg.eigvals(floquet_map(p,chi))
        # The cumulant-generating branch is the multiplier continuously connected
        # to the trace-preserving eigenvalue 1 at chi=0.
        k=np.argmin(np.abs(z-1.0))
        return np.log(z[k])/p.period
    lp=lam(h); lm=lam(-h)
    c1=((lp-lm)/(2j*h)).real
    c2=(-(lp+lm)/(h*h)).real
    return float(c1), float(max(c2,0.0)), float(max(c2,0.0)/max(abs(c1),1e-30))


def current_A(p: Params):
    c1,c2,F=counting_cumulants(p)
    return E_CHARGE*c1


def gaussian_counting_fi_rate(p: Params, parameter: str='detuning_rad_s', step: float|None=None):
    """Asymptotic classical Fisher-information rate from the net count N(t),
    using the Gaussian long-time counting statistics: Fdot=(dc1/dtheta)^2/c2.
    The omitted derivative-of-variance term is O(t^0) and does not contribute to the
    extensive long-time FI rate.
    """
    val=getattr(p,parameter)
    if step is None:
        scale=max(abs(val),1.0)
        step=1e-4*scale
        if parameter=='detuning_rad_s': step=2*np.pi*2e4
        if parameter=='Omega_F': step=2*np.pi*2e4
    pp=replace(p, **{parameter: val+step}); pm=replace(p, **{parameter: val-step})
    c1p,_,_=counting_cumulants(pp); c1m,_,_=counting_cumulants(pm)
    dc=(c1p-c1m)/(2*step)
    _,c2,_=counting_cumulants(p)
    return float(dc*dc/max(c2,1e-30))


def bloch_vector(rho):
    # conditional on singly occupied charge sector
    ps=(rho[1,1]+rho[2,2]).real
    if ps<1e-15: return np.array([0.,0.,0.]), ps
    r=np.array([2*rho[1,2].real, -2*rho[1,2].imag, (rho[1,1]-rho[2,2]).real])/ps
    return r,ps


def qubit_qfi_from_bloch(r, dr):
    r=np.asarray(r,float); dr=np.asarray(dr,float)
    n2=float(r@r); a=float(dr@dr)
    if n2<1-1e-10:
        return a + float(r@dr)**2/max(1-n2,1e-15)
    # pure-state limit when derivative tangential
    return a


def periodic_state_qfi(p: Params, parameter='detuning_rad_s', step=None):
    val=getattr(p,parameter)
    if step is None:
        step=2*np.pi*2e4 if parameter in ('detuning_rad_s','Omega_F') else 1e-4*max(abs(val),1.0)
    rho,_,_=periodic_steady_state(p)
    rp,ps=bloch_vector(rho)
    r1,_,_=periodic_steady_state(replace(p,**{parameter:val+step}))
    r2,_,_=periodic_steady_state(replace(p,**{parameter:val-step}))
    bp,_=bloch_vector(r1); bm,_=bloch_vector(r2)
    dr=(bp-bm)/(2*step)
    return qubit_qfi_from_bloch(rp,dr), ps


# ---------------- analytic reduced model ----------------
def analytic_bloch_matrix(delta, Omega_F, Gamma1, Gamma2):
    return np.array([[-Gamma2, -delta, 0.0],
                     [ delta, -Gamma2, -Omega_F],
                     [0.0, Omega_F, -Gamma1]], float)


def analytic_ep(Gamma1, Gamma2):
    return 0.5*abs(Gamma1-Gamma2)


def analytic_eigenvalues_on_resonance(Omega_F,Gamma1,Gamma2):
    root=np.sqrt(((Gamma1-Gamma2)/2)**2-Omega_F**2+0j)
    return np.array([-Gamma2, -(Gamma1+Gamma2)/2+root, -(Gamma1+Gamma2)/2-root])


def dlt_bloch_dissipator(r, Gamma_D, pol, m):
    """Spin-only dissipative torque from a polarized Markovian bath.

    For jump rates gamma_+=(Gamma_D/2)(1+pol), gamma_-=(Gamma_D/2)(1-pol)
    in the m basis, dr/dt = -Gamma_D/2 r - Gamma_D/2 (m.r)m + Gamma_D pol m.
    """
    r=np.asarray(r,float); m=np.asarray(m,float); m=m/np.linalg.norm(m)
    return -0.5*Gamma_D*r - 0.5*Gamma_D*np.dot(m,r)*m + Gamma_D*pol*m


def floquet_mode_data(p: Params):
    """Return Floquet exponents and right-eigenvector diagnostics.

    Each entry contains exponent ``mu``, multiplier ``z``, normalized right vector,
    a spin-sector weight, and a charge-sector weight.  The weights are diagnostics,
    not probabilities; they are used only to identify spin-like decay modes among
    charge-relaxation modes of the four-state model.
    """
    Phi = floquet_map(p, 0.0)
    z, R = eig(Phi)
    mu = np.log(z) / p.period
    im = (mu.imag + 0.5*p.omega) % p.omega - 0.5*p.omega
    mu = mu.real + 1j*im
    out = []
    for k in range(len(z)):
        v = R[:, k]
        nv = np.linalg.norm(v)
        if nv > 0:
            v = v / nv
        # OP_BASIS order: 00, uu, ud, du, dd, 22
        sx = v[2] + v[3]
        sy = 1j*(v[2] - v[3])
        sz = v[1] - v[4]
        spin = np.sqrt(abs(sx)**2 + abs(sy)**2 + abs(sz)**2)
        yz = np.sqrt(abs(sy)**2 + abs(sz)**2)
        charge = np.sqrt(abs(v[0])**2 + abs(v[1]+v[4])**2 + abs(v[5])**2)
        out.append(dict(mu=mu[k], z=z[k], vector=v,
                        spin_weight=float(spin), yz_weight=float(yz),
                        sx_weight=float(abs(sx)), charge_weight=float(charge)))
    return out


def spin_like_modes(p: Params, n: int = 3):
    """Select the slowest nonstationary modes with appreciable spin character."""
    data = floquet_mode_data(p)
    cand = [d for d in data if abs(d['mu']) > 1e-3 and d['spin_weight'] > 1e-6]
    # Prioritize spin purity, but within the spin-like set retain slow dynamics.
    cand.sort(key=lambda d: (-d['spin_weight']/(d['charge_weight']+1e-12),
                             abs(d['mu'].real), abs(d['mu'].imag)))
    chosen = cand[:max(n, 3)]
    chosen.sort(key=lambda d: (abs(d['mu'].real), abs(d['mu'].imag)))
    return chosen[:n]


def spin_pair_diagnostics(p: Params):
    """Closest pair among the three principal spin-like Floquet modes.

    Returns (separation [s^-1], right-eigenvector overlap, mu1, mu2).  At a genuine
    second-order EP the separation tends to zero and the normalized right-vector
    overlap tends to one.
    """
    data = floquet_mode_data(p)
    cand = [d for d in data if abs(d['mu']) > 1e-3 and d['yz_weight'] > 1e-7]
    # The resonant Hamiltonian drive is along x, so the critical pair lives in the
    # y-z sector; the decoupled x-coherence mode is deliberately excluded.
    cand.sort(key=lambda d: -d['yz_weight'])
    modes = cand[:2]
    if len(modes) < 2:
        return np.nan, np.nan, np.nan+0j, np.nan+0j
    vi, vj = modes[0]['vector'], modes[1]['vector']
    sep = abs(modes[0]['mu'] - modes[1]['mu'])
    ov = abs(np.vdot(vi, vj))/(np.linalg.norm(vi)*np.linalg.norm(vj))
    return float(sep), float(ov), modes[0]['mu'], modes[1]['mu']


def stroboscopic_trace(p: Params, rho0: NDArray[np.complex128], n_periods: int,
                       stride: int = 1):
    """Propagate a density matrix at integer multiples of the drive period."""
    Phi = floquet_map(p, 0.0)
    v = rho_to_vector(rho0)
    ts, rs, occ = [], [], []
    for n in range(n_periods + 1):
        if n % stride == 0:
            rho = vector_to_rho(v)
            rho = (rho + rho.conj().T)/2
            tr = np.trace(rho).real
            if abs(tr) > 1e-15:
                rho = rho/tr
            r, ps = bloch_vector(rho)
            ts.append(n*p.period); rs.append(r); occ.append(ps)
        v = Phi @ v
    return np.asarray(ts), np.asarray(rs), np.asarray(occ)


def periodic_cycle(p: Params, n_steps: int | None = None):
    """Return the periodic steady state resolved over one rf cycle."""
    rho0, _, _ = periodic_steady_state(p)
    v = rho_to_vector(rho0)
    n = n_steps or p.steps_per_period
    dt = p.period/n
    ts = [0.0]; rs = []; occ = []
    r, ps = bloch_vector(rho0); rs.append(r); occ.append(ps)
    for k in range(n):
        tmid = (k+0.5)*dt
        v = expm(reduced_superop(tmid, p, 0.0)*dt) @ v
        rho = vector_to_rho(v)
        rho = (rho + rho.conj().T)/2
        rho /= np.trace(rho).real
        r, ps = bloch_vector(rho)
        ts.append((k+1)*dt); rs.append(r); occ.append(ps)
    return np.asarray(ts), np.asarray(rs), np.asarray(occ)


def right_count_rate(rho: NDArray[np.complex128], t: float, p: Params) -> float:
    """Instantaneous signed electron transfer rate into the right electrode."""
    rate = 0.0
    for C, q in _raw_jumps_for_lead('R', t, p):
        if q:
            rate += q * np.trace(C @ rho @ C.conj().T).real
    return float(rate)


def cycle_averaged_current(p: Params) -> float:
    """Period-averaged right-lead current (A) from the periodic steady state."""
    rho0, _, _ = periodic_steady_state(p)
    v = rho_to_vector(rho0)
    n = p.steps_per_period
    dt = p.period/n
    rates = []
    for k in range(n):
        tmid = (k+0.5)*dt
        # half-step gives a midpoint state for the current evaluation
        L = reduced_superop(tmid, p, 0.0)
        vh = expm(L*(0.5*dt)) @ v
        rhoh = vector_to_rho(vh)
        rates.append(right_count_rate(rhoh, tmid, p))
        v = expm(L*dt) @ v
    return E_CHARGE * float(np.mean(rates))


# ---------------------------------------------------------------- EP location (v7)
def ep_pair_full_diagnostics(p: Params):
    """Diagnostics of the critical y-z pair beyond eigenvalue separation.

    Returns a dict with the pair separation ``sep`` (s^-1), the normalised separation
    ``sep_norm = |mu1-mu2|/(|mu1|+|mu2|)``, the right-eigenvector overlap ``overlap``,
    the real discriminant ``disc = Re[(mu1-mu2)^2]`` (negative on the underdamped side,
    positive on the overdamped side), the phase rigidities ``rig1, rig2`` of the two
    modes, r_j = |L_j^dagger R_j| / (||L_j|| ||R_j||), which vanish at an EP, and the
    condition number ``cond`` of the right-eigenvector matrix of the one-period map,
    which diverges at an EP.
    """
    data = floquet_mode_data(p)
    cand = [d for d in data if abs(d['mu']) > 1e-3 and d['yz_weight'] > 1e-7]
    cand.sort(key=lambda d: -d['yz_weight'])
    modes = cand[:2]
    Phi = floquet_map(p, 0.0)
    z, R = eig(Phi)
    L = np.linalg.inv(R).conj().T          # columns: left eigenvectors, L^dagger R = 1
    def rigidity(v):
        k = int(np.argmin(np.linalg.norm(R - v[:, None], axis=0)))
        return float(abs(np.vdot(L[:, k], R[:, k]))/(np.linalg.norm(L[:, k])*np.linalg.norm(R[:, k])))
    mu1, mu2 = modes[0]['mu'], modes[1]['mu']
    v1, v2 = modes[0]['vector'], modes[1]['vector']
    d = mu1 - mu2
    return dict(sep=float(abs(d)), sep_norm=float(abs(d)/(abs(mu1)+abs(mu2))),
                overlap=float(abs(np.vdot(v1, v2))), disc=float((d*d).real),
                rig1=rigidity(v1), rig2=rigidity(v2), cond=float(np.linalg.cond(R)),
                mu1=mu1, mu2=mu2)


def locate_ep(p: Params, f_lo_MHz: float, f_hi_MHz: float, xtol_MHz: float = 1e-9):
    """Locate the coherent-drive EP by a bracketed root of the real discriminant.

    On resonance and for real spinors the one-period map is similar to a real matrix,
    so the critical pair is either complex-conjugate (Re[(mu1-mu2)^2] < 0) or real
    (Re[(mu1-mu2)^2] > 0).  The sign change is linear in Omega_F, so a bracketed root
    converges to machine precision, whereas minimising |mu1-mu2| stalls on the
    square-root cusp.  Returns (f_EP in MHz, diagnostics at f_EP).
    """
    from scipy.optimize import brentq
    TWOPI = 2*np.pi
    def disc(f):
        return ep_pair_full_diagnostics(replace(p, Omega_F=TWOPI*f*1e6))['disc']
    # coarse bracket search
    fs = np.linspace(f_lo_MHz, f_hi_MHz, 25)
    gs = np.array([disc(f) for f in fs])
    idx = np.where(np.sign(gs[:-1]) != np.sign(gs[1:]))[0]
    if len(idx) == 0:
        raise RuntimeError('no discriminant sign change in bracket')
    i = idx[-1]
    f_ep = brentq(disc, fs[i], fs[i+1], xtol=xtol_MHz, maxiter=200)
    return f_ep, ep_pair_full_diagnostics(replace(p, Omega_F=TWOPI*f_ep*1e6))
